### PR TITLE
imagefactory: Add ability to create hyperv and vagrant images

### PR DESCRIPTION
**Pull request by baude**
We can now output hyperv images and two forms of vagrant images.  For
hyper-v, we can output a Gen1 image that can be imported into a hyper-v
Gen1 VM.  The image lacks the OVA tagging and format because MS deviates
from the standrard as we know it.  For vagrant, we can now produce a
libvirt-based image and a virtualbox-base image.

* imagefactory:
    - Addition of -i hyperv -i vagrant-libvirt -i vagrant-virtualbox
    - Vagrant images require an additional kickstart which can be
      referred to with --vkickstart
    - Broke out several new functions from the create() to efficiently
      deal with building two base images when vagrant images are
      desired. i.e. generateOVA(), formatKS()

### CODE REVIEW

**Comment by cgwalters** [comment]
I tried creating a vagrant-virtualbox, and it produced a `.box` file, but `vagrant add` on OS X complained it was missing a metadata.json.  

    # tar tf rhel-atomic-host-7-vagrant-virtualbox.box 
    desc.ovf
    disk.img

**Comment by cgwalters** [comment]
This turned out to be an old imagefactory.  Is this PR good to go then from your POV?

**Comment by baude** [comment]
@cgwalters yeah.  there might a slight tweak here or there but nothing big.

**Comment by cgwalters** [comment]
Ok, let's do any fixes as followups then, thanks!  :+1:

**Pull request merged**
