### PR TITLE
pxetolive: don't require ks and tdl when image is supplied

### PR DESCRIPTION
**Pull request by rvykydal**

### CODE REVIEW

**Comment by baude** [comment]
Looks good to me, will merge unless Colin has objections.  Good catch Radek.

**Comment by cgwalters** [comment]
It seems fine to me, what's the use case for the existing image though?  Is this a developer fast path?  

Regardless :+1:

**Comment by baude** [comment]
One user case would be a developer fast path, but also, if you happen to make a RAW live image elsewhere, it's trivial to import (reuse)

**Comment by rvykydal** [comment]
My use case (where I came across the issue) was developer debugging, I was building live image from the RAW image using lmc directly and then with toolbox). It is true that the only parametrization of the second step (RAW -> live) could be setting the size of rootfs (which it is not exposed to rpm-ostree-toolbox now). Other options might appear in the future though.
And yes, option to reuse existing RAW image can be useful.

**Pull request merged**
