### PR TITLE
[merged] Add `ostree_remote` config option

### PR DESCRIPTION
**Pull request by cgwalters**
For [CAHC](https://wiki.centos.org/SpecialInterestGroup/Atomic/Devel)
I want to use the base `centos-atomic-host` osname, but
use `centos-atomic-continuous` as the ostree remote name.

### CODE REVIEW

**Comment by giuseppe** [comment]
LGTM

**Comment by cgwalters** [comment]
@giuseppe I think we have homu enabled here.

**Comment by jlebon** [comment]
@cgwalters Whoops, sorry totally missed that. LGTM, but I'll let @giuseppe do the honours since I'm not familiar at all yet with the r-o-t codebase.

**Comment by jlebon** [comment]
Actually, that's pretty easy to grok regardless (yay Python!).
@rh-atomic-bot r+ 60a4b41

**Pull request closed without merging**
